services:

  mysql:
    image: mysql:8.0
    container_name: hrms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrms_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: hrms-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: hrms-kafka
    ports:
      - "9092:9092"

  hrms-app:
    image: enterprise-hrms:latest
    container_name: hrms-app
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    depends_on:
      mysql:
          condition: service_healthy
      redis:
          condition: service_started
      kafka:
          condition: service_started


volumes:
    mysql-data:
